service: monitoring

provider:
  name: aws
  runtime: python3.10
  region: eu-central-1
  environment:
    MONITOR_MONGO_URI: ${env:MONITOR_MONGO_URI}

    FOOD_STAGING_URI: ${env:FOOD_STAGING_URI}
    FOOD_LIVE_URI: ${env:FOOD_STAGING_URI}
    OLX_URI: ${env:OLX_URI}

    FOOD_STAGING_DB: ${env:FOOD_STAGING_DB}
    FOOD_LIVE_DB: ${env:FOOD_LIVE_DB}
    OLX_DB: ${env:OLX_DB}

package:
  exclude:
    - ./**
  include:
    - aws_handlers.py

custom:
  pythonRequirements:
    fileName: requirements.txt
    pythonBin: python
    useDownloadCache: true

functions:
  supply:
    handler: aws_handlers.all_monitor
    events:
      - schedule: rate(6 hours)

plugins:
  - serverless-python-requirements
